language: php
php:
- '5.6'
- '7.0'
script: php generator/run.php
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://${GH_TOKEN}@github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist
  --tags
- ls -R
deploy:
  provider: releases
  api_key:
    secure: MllgoJwOTJ00ZCDvgU5XHHtyJ9mRhROX3dZ23WCsSCOPk/fKTsdzWEiS46yXYSdZfy5gQGHftP0Htdt/h9LgQmd7KjxG1wdAohwFAnRUZCbOxfGc795r0U0lDWnj2Rx3zQyix06PyqYNjBK2cvBelOWX8SqBf8KPxXV0r8HAu2Y=
  file:
  - .htaccess
  - referral-spam.conf
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except:
  - /^*-v[0-9]/
env:
  global:
  - secure: MllgoJwOTJ00ZCDvgU5XHHtyJ9mRhROX3dZ23WCsSCOPk/fKTsdzWEiS46yXYSdZfy5gQGHftP0Htdt/h9LgQmd7KjxG1wdAohwFAnRUZCbOxfGc795r0U0lDWnj2Rx3zQyix06PyqYNjBK2cvBelOWX8SqBf8KPxXV0r8HAu2Y=
  - secure: A1du44fKxNh/cRA63rmh+HXQ1BiFK7yJWQjSufGSzGF+JJ+2sH0mUQkKE7dyJ8qiYz1OQyUeUY9Igbdb3Ar4qriN+zW8tqYoGjvY+8f+oSwn/1rAsI/gGSKGnzWQJVUVrJyeNkQnITYrx6WsBMJs1sbTaC1aAgT7zpNeigG9Q4Y=
